---
JavaScript:
  beautifiers:
  - Prettier
  - Pretty Diff
  - JS-Beautify
  - ESLint
  arrow_parens: as-needed
  brace_style: collapse
  break_chained_methods: false
  comma_first: true
  end_with_newline: false
  indent_comments: false
  indent_size: 2
  indent_style: space
  jslint_happy: true
  multiline_ternary: never
  object_curly_spacing: false
  pragma_insert: false
  pragma_require: false
  preserve_newlines: false
  quotes: single
  remove_trailing_whitespace: true
